version: "3"
services:
  aleo_game_be:
    image: aleo-game-be
    container_name: aleo_game_be
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:5000
    networks:
      - base-network
    command: gunicorn --bind 0.0.0.0:5000 --workers=2 --worker-class=uvicorn.workers.UvicornWorker main:app --log-level=debug -c conf/gunicorn.py --timeout 0

networks:
  base-network:
    external: true