"""INIT DB

Revision ID: 25e35d6217de
Revises: 
Create Date: 2023-10-18 10:03:20.113325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e35d6217de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('tenant', sa.String(), nullable=False),
    sa.Column('va_account', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atom_va_reconcile',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transactions', sa.JSON(), nullable=True),
    sa.Column('total_txn', sa.BigInteger(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atom_va_transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bank_account_customer', sa.String(), nullable=False),
    sa.Column('bank_account_receiver', sa.String(), nullable=False),
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('callback_url', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('va_account_customer', sa.String(), nullable=False),
    sa.Column('va_account_receiver', sa.String(), nullable=False),
    sa.Column('va_partner', sa.String(), nullable=False),
    sa.Column('is_reconcile', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('action_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('event_time', sa.String(), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('header_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bic', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('bank_code', sa.String(), nullable=True),
    sa.Column('swift_code', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('va_from_bank', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atom_va_account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bank_account_no', sa.String(), nullable=False),
    sa.Column('bank_id', sa.BigInteger(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('partner', sa.String(), nullable=False),
    sa.Column('va_type', sa.String(), nullable=False),
    sa.Column('va_partner', sa.String(), nullable=False),
    sa.Column('account_no', sa.String(), nullable=True),
    sa.Column('callback_url', sa.String(), nullable=True),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('saving_id', sa.BigInteger(), nullable=True),
    sa.Column('va_account_no', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('identification_no', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('bank_id', sa.BigInteger(), nullable=False),
    sa.Column('bank_code', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), server_default=sa.text('50000'), nullable=True),
    sa.Column('account_no', sa.String(), nullable=False),
    sa.Column('expire_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bank_account_customer', sa.BigInteger(), nullable=False),
    sa.Column('bank_account_receiver', sa.BigInteger(), nullable=False),
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.Column('callback_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_customer'], ['bank_account.id'], ),
    sa.ForeignKeyConstraint(['bank_account_receiver'], ['bank_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_va_account',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bank_account', sa.BigInteger(), nullable=False),
    sa.Column('va_account_no', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bank_account'], ['bank_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_va_account')
    op.drop_table('bank_transaction')
    op.drop_table('bank_account')
    op.drop_table('atom_va_account')
    op.drop_table('bank')
    op.drop_table('audit_log')
    op.drop_table('atom_va_transaction')
    op.drop_table('atom_va_reconcile')
    op.drop_table('api_key')
    # ### end Alembic commands ###
