"""add colum in table bank

Revision ID: 4c615e8d38ee
Revises: 25e35d6217de
Create Date: 2023-10-18 14:38:12.522578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c615e8d38ee'
down_revision: Union[str, None] = '25e35d6217de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank', sa.Column('callbank_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank', 'callbank_url')
    # ### end Alembic commands ###
