"""add field 'role' for account

Revision ID: a721d3c59cef
Revises: fcd2b46431a0
Create Date: 2023-10-24 16:11:34.563169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a721d3c59cef'
down_revision: Union[str, None] = 'fcd2b46431a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'role')
    # ### end Alembic commands ###
