"""replace name va_partner

Revision ID: fcd2b46431a0
Revises: c204e4030524
Create Date: 2023-10-22 22:02:12.965982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd2b46431a0'
down_revision: Union[str, None] = 'c204e4030524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atom_va_account', sa.Column('parent_va', sa.String(), nullable=True))
    op.drop_column('atom_va_account', 'va_partner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atom_va_account', sa.Column('va_partner', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('atom_va_account', 'parent_va')
    # ### end Alembic commands ###
